application: webcarcollection
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin/.*
  script: main.py
  login: admin

- url: .*
  script: main.py
